# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

example1 = CourseModule.create(Title: 'Computer Logic', ModuleCode: 'COM1031', ModuleOverview: 'To introduce the fundamental principles of digital logic, circuits and systems starting with symbolic logic through to the concept of logic gates to the structure and operation of digital logic circuits and systems. This module provides an understanding of the underlying computer architecture and internal operation of computer systems.', ModuleLeader: 'JL', ModuleLeaderID: 1, Credits: 15, Year: 1)
example2 = CourseModule.create(Title: 'Programming Fundamentals', ModuleCode: 'COM1027', ModuleOverview: 'This module will provide an introduction to the fundamental concepts of object-oriented programming using Java. ', ModuleLeader: 'SK', ModuleLeaderID: 2, Credits: 15, Year: 1)
example3 = CourseModule.create(Title: 'Web and Database Systems', ModuleCode: 'COM1025', ModuleOverview: 'This module introduces students to key technologies of the World Wide Web (WWW) and Database systems.', ModuleLeader: 'MC' , ModuleLeaderID: 3, Credits: 15, Year: 1)
example4 = CourseModule.create(Title: 'Advanced Algorithms', ModuleCode: 'COM2031', ModuleOverview: 'The module introduces algorithmic techniques for various sets of problems and teaches how to analyse algorithms in terms of their complexity. ', ModuleLeader: 'SS', ModuleLeaderID: 4, Credits: 15, Year: 2)
example5 = CourseModule.create(Title: 'Web Applications Development', ModuleCode: 'COM2025', ModuleOverview: 'This module will demonstrate some of the latest technologies for building interactive web applications', ModuleLeader: 'AC', ModuleLeaderID: 5, Credits: 15, Year: 2)
example6 = CourseModule.create(Title: 'Computer Networking', ModuleCode: 'COM2022', ModuleOverview: 'This module introduces essential concepts about all the computer networking layering levels with some emphasis on the routing algorithms and implementation of network sensing.', ModuleLeader: 'NS', ModuleLeaderID: 6, Credits: 15, Year: 2)
example7 = CourseModule.create(Title: 'Computer Security', ModuleCode: 'COM3009', ModuleOverview: 'This module covers the basic principles behind computer security.', ModuleLeader: 'SS', ModuleLeaderID: 4, Credits: 15, Year: 3)
example8 = CourseModule.create(Title: 'Internet of Things', ModuleCode: 'COM3023', ModuleOverview: 'This module will provide an overview of the key concepts and enabling technologies for the Internet of Things, including: Wireless Sensor Networks, Platforms (Hardware, Software), Machine-to-Machine communications (M2M), protocols and standards (e.g. 6LowPAN, ZigBee, CoAp), semantic technologies, and data and information processing mechanisms.', ModuleLeader: 'MS', ModuleLeaderID: 7, Credits: 15, Year: 3)
example9 = CourseModule.create(Title: 'Mainframe Computing', ModuleCode: 'COM3015', ModuleOverview: 'Mainframe Computing in general provides for an interesting background to, and contrast with, Cloud Computing, and in relation to Business Systems and Distributed Computing more generally.', ModuleLeader: 'AC', ModuleLeaderID: 5, Credits: 15, Year: 3)